version: '3'
services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE} 
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
    volumes:
      - ./:/app/
      
  mysql-db:
    build: ./migrations
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Replace with your password
      MYSQL_USER: myuser
      MYSQL_DATABASE: mydatabase
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data_5:/var/lib/mysql

volumes:
  mysql-data_5: