version: '3'
services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    env_file:
      - .env
    volumes:
      - ./:/app/
      
  mysql-db:
    build: ./migrations
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: